/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.jcraron.pixivcrawler;

import java.io.File;
import java.io.IOException;

import org.apache.http.client.CookieStore;

import net.jcraron.pixivcrawler.controller.MainController;
import net.jcraron.pixivcrawler.pixiv.HPixiv;
import net.jcraron.pixivcrawler.pixiv.PixivHttpHandle;
import net.jcraron.pixivcrawler.util.CookieLoader;
import net.jcraron.pixivcrawler.util.IOUtil;
import net.jcraron.pixivcrawler.util.exception.DecryptException;

public class App {
	static PixivHttpHandle httpHandle = null;
	static HPixiv pixiv = null;

	public static void main(String[] args) throws Exception {
//		pivix();
		MainController.main(new File("D:\\crawler\\pixiv"));
		
	}

	public static CookieStore decryptCookieStore() throws IOException, DecryptException {
		File originCookies = new File(CookieLoader.WINDOWS_CHROME_COOKIE_PATH);
		File originMasterKey = new File(CookieLoader.WINDOWS_CHROME_MASTER_KEY_PATH);

		File copyCookies = new File("originCookies");
		File copyMasterKey = new File("originMasterkey");
		IOUtil.copy(originCookies, copyCookies);
		IOUtil.copy(originMasterKey, copyMasterKey);
		CookieStore cookstore = CookieLoader.readChromeCookies(copyCookies, copyMasterKey, "host_key LIKE '%pixiv%'");
		copyCookies.delete();
		copyMasterKey.delete();
		return cookstore;
	}

	public static void pivix() throws Exception {
		File file = new File("cookieStore");
		if (file.exists()) {
			IOUtil.loadObjects(file, (in) -> httpHandle = (PixivHttpHandle) in.readObject());
			pixiv = new HPixiv(httpHandle);
		} else {
			pixiv = new HPixiv(new PixivHttpHandle(decryptCookieStore()));
		}
		IOUtil.saveImage(new File("kk.zip"), pixiv.getImageInfo("96749449").getImages().next(), true);
		IOUtil.saveObjects(file, (out) -> out.writeObject(pixiv.getHttpHandle()));
		pixiv.getHttpHandle().close();
	}
	
}
